# Generated by Django 5.0.3 on 2025-11-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainActuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_no', models.CharField(max_length=50)),
                ('line_item', models.CharField(max_length=50)),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('cylinder_size', models.CharField(help_text='Cylinder size in inch', max_length=50)),
                ('spring_size', models.CharField(blank=True, max_length=50, null=True)),
                ('moc', models.CharField(help_text='Material of Construction', max_length=50)),
                ('order_qty', models.CharField(default='0', max_length=50)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('under_assembly', 'Under Assembly'), ('under_testing', 'Under Testing'), ('under_painting', 'Under Painting'), ('under_finishing', 'Under Finishing'), ('under_qa', 'Under QA'), ('finished_goods', 'Finished goods')], default='pending', max_length=20)),
                ('item_code', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
                ('branch', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembler_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, null=True)),
                ('actuator_serial_no', models.CharField(max_length=100, unique=True)),
                ('housing_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('yoke_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('top_cover_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('da_side_adaptor_plate_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('spring_side_adaptor_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('da_side_end_plate_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('spring_side_end_plate_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembler_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='manufacturing.mainactuator')),
            ],
        ),
    ]
