# Generated by Django 5.0.3 on 2025-11-21 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails25Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembler_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, null=True)),
                ('actuator_serial_no', models.CharField(max_length=100, unique=True)),
                ('housing_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('yoke_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('top_cover_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('da_side_adaptor_plate_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('spring_side_adaptor_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('da_side_end_plate_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('spring_side_end_plate_heat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembler_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details_25', to='manufacturing.mainactuator')),
            ],
            options={
                'verbose_name': 'Order Details (25 Series)',
                'verbose_name_plural': 'Order Details (25 Series)',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails21Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(help_text='Auto-generated as OrderNo-SrNo format', max_length=100, unique=True)),
                ('assembler_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, null=True)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('end_cap_right', models.CharField(blank=True, max_length=100, null=True)),
                ('end_cap_left', models.CharField(blank=True, max_length=100, null=True)),
                ('pinion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembler_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details_21', to='manufacturing.mainactuator')),
            ],
            options={
                'verbose_name': 'Order Details (21 Series)',
                'verbose_name_plural': 'Order Details (21 Series)',
            },
        ),
    ]