# Generated by Django 5.0.3 on 2025-11-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_add_series_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]