# Generated by Django 5.0.3 on 2025-11-21 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_remove_original_orderdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails21Series',
            new_name='OrderDetails_21_Series',
        ),
        migrations.RenameModel(
            old_name='OrderDetails25Series',
            new_name='OrderDetails_25_Series',
        ),
    ]
