# Generated by Django 5.0.3 on 2025-11-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_rename_orderdetails21series_orderdetails_21_series_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails_21_series',
            old_name='sr_no',
            new_name='actuator_serial_no',
        ),
    ]
